### ISSUE TITLE
Zen系列还没有完全开源，现在版权仍在于A1，建议下架

### ISSUE THREAD

**Issue by Skr-ZERO** [max32002/maruko-gothic#1]
![QQ图片20210719162339](https://user-images.githubusercontent.com/62774986/126127719-5c0634ca-33d8-45ac-ad22-9a993f271e79.jpg)

**Comment by max32002** [comment]
感謝，先設為不公開專案。

**Comment by max32002** [comment]
目前Zen已開源，感謝提醒。
